#!/bin/sh
set -e
set -u

fn_help() { (
    echo >&2 "Usage: ./mariadb-restore <env-file> <bak-file>"
    echo >&2 "Example: ./mariadb-restore ./prod.env /mnt/storage/prod-db/backup-2023-08-30.sql.xz"
); }

my_env_file="${1:-}"
if ! test -n "${my_env_file}"; then
    fn_help
    exit 1
fi
my_bak_file="${2:-}"
if ! test -n "${my_bak_file}"; then
    fn_help
    exit 1
fi
if test -e "${my_env_file}"; then
    #shellcheck disable=SC1090
    . "${my_env_file}"
fi

if test -z "${DB_URL}"; then
    echo "Error: missing DB_URL"
    exit 1
fi
my_user="$(echo "${DB_URL}" | cut -d'@' -f1 | sed 's://::' | cut -d':' -f2)"
my_pass="$(echo "${DB_URL}" | cut -d'@' -f1 | sed 's://::' | cut -d':' -f3)"
my_host="$(echo "${DB_URL}" | cut -d'@' -f2 | cut -d'/' -f1)"
my_dbname="$(echo "${DB_URL}" | cut -d'@' -f2 | cut -d'/' -f2)"

read -p "DESTROY database '${my_user}@${my_host}/${my_dbname}'?!"
read -p "Are you sure?!?!"
sudo mysql -u root -e "
    DROP DATABASE ${my_dbname};
    CREATE DATABASE ${my_dbname};
";

# gunzip -c "${my_bak_file}" |
#    sudo mysql -u root "${my_dbname}";
unxz -c "${my_bak_file}" |
    sudo mysql -u root "${my_dbname}";
