#!/bin/sh
set -e
set -u

# curl https://webi.sh/serviceman | sh

# may need --path "${PATH}" if other bins are needed in the PATH
sudo env PATH="$PATH" \
    serviceman add --system --username "$(id -u -n)" --name 'mariadb-backup' ./mariadb-backup-runner
