#!/bin/sh
set -e
set -u

my_country="US"
my_state="Utah"
my_locality="Provo"
my_cert_cn="example.com"

fn_gen_keys() { (
    if test -e /etc/mysql-ssl; then
        echo "TLS Certs exist: /etc/mysql-ssl"
        return 0
    fi

    mkdir -p ./mysql-ssl/
    cd ./mysql-ssl/ || return 1

    # ignore "Can't load /root/.rnd into RNG"

    echo "gen key"
    openssl genrsa 2048 > ./ca-key.pem

    echo "gen req"
    openssl req -new -x509 -nodes -sha256 -days 36500 \
        -key ./ca-key.pem -out ./ca-cert.pem \
        -subj "/C=${my_country}/ST=${my_state}/L=${my_locality}/CN=${my_cert_cn}"

    #echo "rsa decrypt"
    #openssl rsa -in ./server-key.pem -out ./server-key.pem

    echo "self req"
    openssl req -newkey rsa:2048 -days 3650 -nodes \
        -keyout ./server-key.pem -out ./server-req.pem \
        -subj "/C=${my_country}/ST=${my_state}/L=${my_locality}/CN=${my_cert_cn}"

    echo "sign"
    openssl x509 -req -in ./server-req.pem -days 3650 \
        -CA ./ca-cert.pem -CAkey ./ca-key.pem -set_serial 01 \
        -out ./server-cert.pem

    openssl rehash ./ca-*
); }

fn_move_certs() {(
    if ! test -e ./mysql-ssl/; then
        return 0
    fi

    sudo chown -R mysql:mysql ./mysql-ssl/
    sudo chmod 0700 ./mysql-ssl/*-key.pem
    sudo chmod 0700 ./mysql-ssl/
    sudo rm -rf /etc/mysql-ssl/
    sudo mv ./mysql-ssl/ /etc/
)}

fn_settls() { (
    my_tls_conf="$(
        sudo grep -r -E '^#\s*ssl-ca\s*=' /etc/mysql/ |
            cut -d':' -f1 |
            sort -u |
            grep -v client ||
            true
    )"
    echo "Checking for TLS cert in ${my_tls_conf}..."
    if ! test -n "${my_tls_conf}"; then
        echo "Found"
        return 0
    fi

    # TODO add 'tls_version = TLSv1.2,TLSv1.3'
    sudo sed -i -e 's:^#\s*ssl-ca\s*=.*:ssl-ca   = /etc/mysql-ssl/ca-cert.pem:g' "${my_tls_conf}"
    sudo sed -i -e 's:^#\s*ssl-cert\s*=.*:ssl-cert = /etc/mysql-ssl/server-cert.pem:g' "${my_tls_conf}"
    sudo sed -i -e 's:^#\s*ssl-key\s*=.*:ssl-key  = /etc/mysql-ssl/server-key.pem:g' "${my_tls_conf}"

    sudo systemctl restart mariadb
    echo "Enabled"
); }

fn_checktls() { (
    my_username='username'
    my_password='password'

    echo "Checking 'have_ssl' is enabled..."
    my_mysql_tls="$(
        mysql -u "${my_username}" -p"${my_password}" databasename -e "SHOW VARIABLES LIKE '%ssl%';"
    )"

    echo "${my_mysql_tls}" |
        grep "have_ssl"

    echo "${my_mysql_tls}" |
        grep "have_ssl.*YES" ||
        (echo "MariaDB TLS Failure" && exit 1)
); }

fn_setbind() { (
    my_bind="$(
        sudo grep -r -E '^\s*bind-address\s*=\s*0.0.0.0' /etc/mysql ||
            true
    )"
    if test -n "${my_bind}"; then
        echo "Bind already enabled"
        echo "${my_bind}"
        return 0
    fi

    my_bind_conf="$(
        sudo grep -r -E '#?\s*bind-address\s*=\s*' /etc/mysql |
            grep -v galera |
            cut -d':' -f1 |
            sort -u ||
            true
    )"
    echo "Checking for 'bind-address' in '${my_bind_conf}'..."
    if test -n "${my_bind_conf}"; then
        echo "Setting 'bind-address = 0.0.0.0' in '${my_bind_conf}'..."

        sudo sed -i -e 's:\s*bind-address\s*=.*:bind-address            = 0.0.0.0:g' "${my_bind_conf}"
        sudo systemctl restart mariadb
    fi
); }

echo ""
fn_gen_keys
fn_move_certs
fn_settls
fn_checktls
fn_setbind
echo ""
echo "Done"
echo ""
